version: '3'
services:
  # app:
  #   build:
  #     context: ./      
  #     dockerfile: docker/app.dev.dockerfile    
  #   working_dir: /src
  #   volumes:                        
  #     - .:/src
  #   ports:
  #     - 5000:5000
  
  db:
    image: mysql:8.0
    volumes:
      - ./tmp/db:/var/lib/mysql
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "33068:3306"
    logging:
      driver: none 

  # redis:
  #   image: "redis:latest"
  #   volumes:
  #     - "./tmp/redis:/data"
  #   logging:
  #     driver: none